DotNetTest/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DotNetTest.Models;
using Microsoft.AspNet.Identity;

namespace DotNetTest.Controllers
{
    [Authorize(Roles = "admin", Users = "admin@gmail.com")]
    public class userController : Controller
    {
        private Default_Entities db = new Default_Entities();
        private MULTIPLE_CHOICE_Entities db2 = new MULTIPLE_CHOICE_Entities();

        // GET: user
        public ActionResult Index()
        {
            var listUser = new List<InfoUser>();
            using (db)
            {
                listUser = (from u in db.AspNetUsers
                            where u.Email != "admin@gmail.com"
                            select new InfoUser
                            {
                                Id = u.Id,
                                Email = u.Email,
                            }).ToList();
            }
            return View(listUser);
        }

        // GET: user/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db2.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: subjects/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db2.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,Email,phone,birthday,gender,student_number,role_name,active")] user user)
        {
            if (ModelState.IsValid)
            {
                db2.Entry(user).State = EntityState.Modified;
                db2.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

    }
}

DotNetTest/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.GetUserName() == "admin@gmail.com")
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Người dùng", "Index", "user")</li>
                    </ul>
                }
                @if (User.Identity.GetUserName() == "admin@gmail.com" || User.Identity.GetUserName() == "lecturer@gmail.com")
                {
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Môn học", "Index", "subjects")</li>
                <li>@Html.ActionLink("Câu hỏi", "Index", "questions")</li>
                <li>@Html.ActionLink("Câu trả lời", "Index", "answers")</li>
                <li>@Html.ActionLink("Bài thi", "Index", "exams")</li>
                <li>@Html.ActionLink("Điểm thi", "Index", "scores")</li>
            </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>